---
# vim: et:ts=2:sw=2:sts=2

- hosts: server

  tasks:
    - name: install nginx
      become: yes
      package:
        state=present
        name=nginx

    - name: remove unnecessary files
      become: yes
      file:
        path=/etc/nginx/{{ item }}
        state=absent
      with_items:
        - default.d
        - fastcgi.conf
        - fastcgi.conf.default
        - fastcgi_params
        - fastcgi_params.default
        - koi-utf
        - koi-win
        - mime.types.default
        - nginx.conf.default
        - scgi_params
        - scgi_params.default
        - uwsgi_params
        - uwsgi_params.default
        - win-utf

    - name: configure nginx
      become: yes
      copy:
        src: files/{{ item }}
        dest: /etc/nginx/{{ item }}
      with_items:
        - mime.types
        - ssl.conf
        - nginx.conf
      register: nginx_restart

    - name: create conf.d
      become: yes
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: 0755

    - name: create ssl folder
      become: yes
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: nginx
        group: nginx
        mode: 0700

    - name: generate dhparam
      become: yes
      become_user: nginx
      shell: openssl dhparam -out dhparam.pem 4096
      args:
        chdir: /etc/nginx/ssl
        creates: dhparam.pem
      register: nginx_restart

    - name: set dhparam owner
      become: yes
      file:
        path=/etc/nginx/ssl/dhparam.pem
        state=file
        owner=nginx
        group=nginx
        mode=0400

    - name: host configuration
      become: yes
      template:
        src=host.conf
        dest=/etc/nginx/conf.d/{{ inventory_hostname }}.conf
      register: nginx_restart

    - name: start nginx
      become: yes
      service:
        name=nginx
        enabled=yes
        state=started

    - name: restart nginx
      become: yes
      service:
        name=nginx
        state=restarted
      when: nginx_restart|changed

# acme configuration
# look at stable.opencast.org (NOT develop...)
# - install acme-tiny
# - generate certificate request
# - enable systemd.service/timer
# - manually start systemd.service once (request initial certificate) if no
#   certificate exists
#
# Note: Path in nginx conf needs to be adjusted

    - name: host https configuration
      become: yes
      template:
        src: host.ssl.conf
        dest: /etc/nginx/conf.d/{{ inventory_hostname }}.https.conf
      notify:
        - reload nginx

  handlers:
    - name: reload nginx
      become: yes
      service:
        name: nginx
        state: restarted
